GoT_wiki/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :houses
  resources :categories
  resources :authors

  root 'welcome#index'

  get '/login', to: 'authors#login'
  get '/login/create', to: 'authors#new'
  post '/login', to: 'authors#login_post'
  get '/logout', to: 'authors#logout'
  get 'authors/:id', to: 'authors#show'

end

GoT_wiki/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
  has_secure_password
end

GoT_wiki/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def login
    if current_author
      redirect_to '/'
    else
      render:login
    end
  end

  def login_post
    @author = Author.find_by({login: params[:login]})
    if @author
      if @author.authenticate(params[:password])
        session[:author_id] = @author.id
        redirect_to "/"
      else
        redirect_to '/login'
      end
    else
      redirect_to '/login'
    end
  end

  def logout
    session[:author_id] = nil
    redirect_to '/login'
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :email, :login, :password)
    end
end

GoT_wiki/app/helpers/authors_helper.rb
module AuthorsHelper
end

GoT_wiki/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

GoT_wiki/app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<% if current_author == @author %>
  <%= render 'form' %>
<% else %>
  <div>You are not authorized to edit this account!!!</div>
<%end%>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

GoT_wiki/app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name.split(' ').map {|e| e.capitalize}.join(' ') %></td>
        <td><%= author.email %></td>
        <td><%= author.login %></td>
        <td><%= link_to 'Show', author %></td>
      </tr>
    <% end %>
  </tbody>
</table>

GoT_wiki/app/views/authors/login.html.erb
<form action='/login' method='post' id = 'login_form'>
  <input type = 'hidden' name = 'authenticity_token' value = '<%=form_authenticity_token%>'/>
  <label for ='login_box'>Login:</label>
  <input type = 'text' name='login' id = 'login_box' class = 'login_form'><br>
  <label for = 'password'>Password:</label>
  <input type = 'password' name = 'password' id = 'password' class = 'login_form'>
  <input type = 'submit' value = 'Log In'>
</form>
<a href = '/login/create'>Don't have a login? Register here!</a>

GoT_wiki/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

GoT_wiki/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @author.login %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<% if current_author == @author %>
  <%= link_to 'Edit', edit_author_path(@author) %>
<% else %>
  <% %>
<%end%>