GoT_wiki/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :houses
  resources :categories
  resources :authors

  root 'welcome#index'

  get '/login', to: 'authors#login'
  get '/login/create', to: 'authors#new'
  post '/login', to: 'authors#login_post'
  get '/logout', to: 'authors#logout'
  get 'authors/:id', to: 'authors#show'

end

GoT_wiki/app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
    @house = House.find(params[:id])
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:id, :house_name, :description, :motto, :symbol_url)
    end
end

GoT_wiki/app/helpers/houses_helper.rb
module HousesHelper
end

GoT_wiki/app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :house_name %><br>
    <%= f.text_field :house_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :motto %><br>
    <%= f.text_field :motto %>
  </div>
  <div class="field">
    <%= f.label :symbol_url %><br>
    <%= f.text_field :symbol_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

GoT_wiki/app/views/houses/edit.html.erb
<h1>Editing House</h1>

<% if session[:author_id] %>
  <%= render 'form' %>
<% else %>
  <%= link_to'You must be logged in to do that!', '/login'%>
<% end %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

GoT_wiki/app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class = 'headline'>The Royal Houses</h1>

<ul>
  <% @houses.order(:house_name).each do |house| %>
    <% if house.house_name == 'not applicable' %>
      <% %>
    <% else %>
        <li class = 'listing'><%= link_to house.house_name.capitalize, house %></li>
    <% end %>
  <% end %>
</ul>
<br>
<div class = 'create'>
  <% if session[:author_id] %>
    <%= link_to 'New House', new_house_path %>
  <% else %>
    <%= link_to'You must be logged in to create new house.', '/login'%>
  <% end %>
</div>

GoT_wiki/app/views/houses/new.html.erb
<h1>New House</h1>

<% if session[:author_id] %>
  <%= render 'form' %>
<% else %>
  <%= link_to'You must be logged in to do that!', '/login'%>
<% end %>
<br>
<%= link_to 'Back', houses_path %>

GoT_wiki/app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>
<img src = '<%= @house.symbol_url %>'/>

<h1><strong>House <%= @house.house_name.capitalize %></strong></h1>

<div class = 'content'>
  <p>
    <strong>Description:</strong>
    <%= @house.description %>
  </p>

  <p><strong>House Motto</strong>: <%= @house.motto %></p>

  <h2>Members of House <%= @house.house_name.capitalize %></h2>
  <ul>
    <% @articles.order(:title).each do |article|%>
      <% if article.house_id == @house.id %>
    <li><%=link_to article.title, article %></li>
      <% end %>
    <% end %>
  </ul>
  <% if session[:author_id] %>
    <%= link_to 'Edit', edit_house_path(@house) %>
  <% else %>
    <%= link_to'You must be logged in to edit', '/login'%>
  <% end %> |
  <%= link_to 'Back', houses_path %>
</div>